version: '2.4'

services:
  loop-garden:
    build:
      context: .
      args:
        app_path: /loop-garden
    container_name: loop-garden
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - .:/loop-garden
    ports:
      - '19000:19000'
      - '19002:19002'
      - '19006:19006'
    command: expo start

